/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_cognito_identity_pool_id": "us-west-1:3ea2e9d3-86b1-446c-b1fc-0d60c3f72522",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_40LTmPHEy",
    "aws_user_pools_web_client_id": "ei2ocph9kgvbkanlvitd6mdhd",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "guruphotos184114-dev",
    "aws_user_files_s3_bucket_region": "us-west-1",
    "aws_appsync_graphqlEndpoint": "https://wpbvmt5yevhlrj2c3pjfyobigm.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
